language: node_js
node_js:
- stable

before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn

install:
- yarn

after_success:
- npm run coveralljs

deploy:
  provider: npm
  email: "micha@famreiser.ch"
  api_key:
    secure: I7qaAN8cz023wjGDA8kAc+GLZFVXnwFux7oH9AmW625oBLAVa950/E6lnOtWBUI87ZTGIhc7fSWzVoA1LIxj/c1c/3JV+rderU3vD/RGU74gmIkn/tfGW2VvuNfsi5CBkeD8PlAEUePDJ6vsDwSRBpFL9/Ur0mD2W88lPrMc5sBbUHMKVLhn24FWPf+y4ETBp8zG5z8fjJVXuNXqPNlz0H3G1VkRRSekcWr6DcshR+hNeV0/AlE9EpsjVTyP3WplyB1ATajvP2WtvMNb3vyy2R37YPazFcFAlXNXGrTBpvSz8yHHpjvhfMqhe7ekdGwDZTOEHZGNc6h5EnRMXCPK3/uMLifixGjt3x/L6X3qH0JBtPT2MDD75B4j79uqYcBgfo1Q2x9O1D/9BMIvbz1Ci0Ca+0H3a4pPE/ejA5vFn6ybdfDFcQBJiYxHxFpm2BAz0isTulMFrxXgW26TH59Vw5D13uYYjKpjC1upS6e9XLOCBUyYE0fF7hwizyCtXxSUaMofmb9iS4kf2yf45FKJJMmAQIcXS3HilxYH3q5Jg/4CWwqpoIUtWoY6jvOnt8W78AoYGttMNKKH2CyFAHyAPfGKGI3szvRk1EBn7K909KJm1lSORlEIyNmc3KKveRGqxT3+w8TPBUxtfCmJkNV2CxNZAdMyu7Vxu2vQJNOwbd0=
  on:
    tags: true
    repo: DatenMetzgerX/babel-plugin-parallel-es
